[package]
name = "translate-bot"
version = "0.1.0"
authors = ["jude-LafiteIII <judewrs@gmail.com>"]

[dependencies]
reqwest = "0.9.1"
serenity = "0.5"
serde = "1.0.79"
serde_derive = "1.0"
serde_json = "1.0"
dotenv = "0.9.0"
lazy_static = "1.1.0"
typemap = "*"
